"""empty message

Revision ID: 874b22e2d8cb
Revises: 54813717e47b
Create Date: 2016-10-07 22:27:18.756895

"""

# revision identifiers, used by Alembic.
revision = '874b22e2d8cb'
down_revision = '54813717e47b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
