"""empty message

Revision ID: 89d5a072beb5
Revises: 178861d67350
Create Date: 2016-10-05 20:52:24.547372

"""

# revision identifiers, used by Alembic.
revision = '89d5a072beb5'
down_revision = '178861d67350'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
